- name: Demonstrates cloning from public GitHub Repository
  hosts: localhost
  vars_files:
  - git-credentials.yml
  tasks:
    - name: Clone TekTutor public GitHub Repo
      git:
       repo: https://{{username}}:{{password}}@github.com/jegantektutordemo/devops-sep-2022.git
       clone: true
       dest: /tmp/ansible/private
       version: main 
